### ISSUE TITLE
honest review.

### ISSUE THREAD

**Issue by amogas** [ARLPLAYZ/Spirit-Boat-#3]
Since there is no review system i will do it here.The bot overall isn't bad at all in fact it does have moderation, automod auto delete etc..... The issue is that it needs a decent hosting service since cheap ones might just make the bot lag and make it unusable for days or even weeks.

**Comment by ARLPLAYZ** [comment]
hosting should be done yourself. There are many cheap hosting services that you can use. 

if you are looking for cheap and reliability you can check out pebblehost

**Comment by amogas** [comment]
so you're using a minecraft hosting service?

**Comment by ARLPLAYZ** [comment]
they have discord bot hosting too

**Comment by amogas** [comment]
that's very cool even tho i will rarely make a bot but if i do i'd stick with my rig and use it as a hosting service if i can.
