### ISSUE TITLE
Deez nuts 

### ISSUE THREAD

**Issue by pspspspspspspsps** [ARLPLAYZ/Spirit-Boat-#4]
Not enough deez nuts jokes if I’m honest

**Comment by amogas** [comment]
DEEZ NUTS

**Comment by amogas** [comment]
![R](https://user-images.githubusercontent.com/85739992/133624775-db96bba3-fbc4-4a84-973e-d8fba3c64aac.jpg)

**Comment by amogas** [comment]
**Bold text**
